const defaultTasks = [
  {
    activity: 'Push-ups',
    repXP: 20,
    reps: '2 x 15',
    duration: 30,
    difficulty: 'Beginner',
    musclesTargeted: ['chest', 'biceps'],
    repId: 'zqtwitxyJ2uczAUAgtU5',
    createdAt: '2020-10-04T01:47:44.816Z',
    complete: false,
    taskType: 'Rep challenge',
    sender: 'Teddy',
    caloriesBurned: 125,
  },
  {
    activity: 'Sit-ups',
    repXP: 30,
    reps: '5 x 4',
    duration: 20,
    difficulty: 'Beginner',
    musclesTargeted: ['abs', 'legs'],
    repId: 'FWha4HurEhsEdgdKjCZh',
    createdAt: '2020-09-26T17:15:34.980Z',
    complete: false,
    taskType: 'Rep challenge',
    sender: 'Teddy',
    caloriesBurned: 125,
  },
  {
    activity: 'Squats',
    repXP: 40,
    reps: '10 x 5',
    duration: 40,
    difficulty: 'Intermediate',
    musclesTargeted: ['chest', 'biceps'],
    repId: 'yCZQ4AnUBLZjKyvHeFBH',
    createdAt: '2020-10-03T14:15:44.494Z',
    complete: false,
    taskType: 'Rep challenge',
    sender: 'Teddy',
    caloriesBurned: 125,
  },
];
