export const nutritionItems = [
    "Fat",
    "Calories",
    "Carbs",
    "Cholesterol",
    "Protein",
    "Sugar",
    "Sodium",
    "Vitamin A",
    "Vitamin C",
    "Calcium",
    "Iron",
    "Vitamin D",
    "Niacin",
    "Potassium",
];

export const mealTypes = ["breakfast", "lunch", "dinner", "snack", "dessert"];

export const mealLabels = [
    "vegan",
    "non-dairy",
    "nut-free",
    "pescatarian",
    "vegeatarian",
    "guten-free",
    "sugar-free",
    "low-cal",
    "meal-prep",
    "healthy choice",
    "quik-n-eazy",
    "low-carb",
];

export const muscles = [
    "abs",
    "arms",
    "chest",
    "biceps",
    "triceps",
    "calves",
    "shins",
    "thighs",
    "glutes",
    "back",
    "shoulders",
    "legs",
    "delts",
    "full body",
];
export const equipment = [
    "dumbbells",
    "kettlebells",
    "medicine ball",
    "barbell",
    "resistance bands",
    "exercise ball",
    "jump rope",
    "stairs",
    "ladder",
    "no equipment",
    "raised platform",
    "pull-up bar",
    "heavy ropes",
];

export const quotes = [
    "“All our dreams can come true, if we have the courage to pursue them.” – Walt Disney",
    "“I’ve missed more than 9,000 shots in my career. I’ve lost almost 300 games. 26 times I’ve been trusted to take the game winning shot and missed. I’ve failed over and over and over again in my life and that is why I succeed.” – Michael Jordan",
    "“Don’t limit yourself. Many people limit themselves to what they think they can do. You can go as far as your mind lets you. What you believe, remember, you can achieve.” – Mary Kay Ash",
    "“It’s hard to beat a person who never gives up.” – Babe Ruth",
    "“If people are doubting how far you can go, go so far that you can’t hear them anymore.” – Michele Ruiz",
    "“Everything you can imagine is real.”― Pablo Picasso",
    "“Do one thing every day that scares you.”― Eleanor Roosevelt",
    "“It’s no use going back to yesterday, because I was a different person then.”― Lewis Carroll",
    "“Happiness is not something ready made. It comes from your own actions.” ― Dalai Lama XIV",
    "“You can either experience the pain of discipline or the pain of regret. The choice is yours.”  – Unknown",
    "“Magic is believing in yourself. If you can make that happen, you can make anything happen.” – Johann Wolfgang Von Goethe",
    "“If something is important enough, even if the odds are stacked against you, you should still do it.” – Elon Musk",
    "“Don’t be afraid to give up the good to go for the great.” – John D. Rockefeller",
    "“People who wonder if the glass is half empty or full miss the point. The glass is refillable.” – Unknown",
    "“You can waste your lives drawing lines. Or you can live your life crossing them.” – Shonda Rhimes",
    "“You’ve got to get up every morning with determination if you’re going to go to bed with satisfaction.” – George Lorimer",
    "“If opportunity doesn’t knock, build a door.” – Kurt Cobain",
    "“Today I will do what others won’t, so tomorrow I can accomplish what others can’t.” —Jerry Rice",
    "“We are what we repeatedly do. Excellence then is not an act but a habit.” —Aristotle",
    "“The difference between the impossible and the possible lies in a person’s determination.” —Tommy Lasorda",
    "“If you want something you’ve never had, you must be willing to do something you’ve never done.” —Thomas Jefferson",
    "“To give anything less than your best is to sacrifice the gift.” —Steve Prefontaine",
    "“Strength does not come from physical capacity. It comes from an indomitable will.” —Mahatma Gandhi",
    "“The last three or four reps is what makes the muscle grow. This area of pain divides the champion from someone else who is not a champion. That’s what most people lack, having the guts to go on and just say they’ll go through the pain no matter what happens.” —Arnold Schwarzenegger",
    "“Don’t count the days, make the days count.” —Muhammad Ali",
    "“Just believe in yourself. Even if you don’t pretend that you do and, and some point, you will.” —Venus Williams",
];
