export const exercise = {
    title: "Lunges",
    difficulty: "3",
    activity: "calisthenics",
    equipment: [],
    motion: "lunges, moderate effort",
    muscles: ["legs", "calfs"],
    schedule: [],
    type: "exercise",
    videoURL:
        "https://firebasestorage.googleapis.com/v0/b/reps-699b0.appspot.com/o/24268207545.mp4?alt=media&token=a7649cc6-e5ea-4359-93fd-d2f1dfe7dd5c",
};

export const workout = {
    title: "First Workout",
    imageURL: "/beachbody.jpg",
    description:
        "First workout to populate the UI & database but I need a bigger description for edge case purposes. You get it. Just hold on tight while I draw up this text really quick so that I can see what a few lines of text does the height of the content container.",
    difficulty: "1",
    type: "workout",
    equipment: [],
    exerciseCount: 2,
    exercises: [
        {
            title: "Lunges",
            activity: "calisthenics",
            motion: "lunges, moderate effort",
            docId: "f1b4e65b-9004-4213-8e6a-b36f83311eb1",
            difficulty: "3",
            duration: "10",
            muscles: ["legs", "calfs"],
            reps: "2x3",
            videoURL:
                "https://firebasestorage.googleapis.com/v0/b/reps-699b0.appspot.com/o/24268207545.mp4?alt=media&token=a7649cc6-e5ea-4359-93fd-d2f1dfe7dd5c",
            type: "exercise",
            status: 0,
            schedule: [],
            referenceId: "MUATNgInAKho3nmIqq5A",
        },
        {
            title: "Push ups",
            activity: "calisthenics",
            difficulty: "2.5",
            docId: "a73b4a82-1b29-4519-aca7-2024a52d877c",
            duration: "10",
            motion: "push ups, moderate effort",
            muscles: ["biceps", "triceps", "chest"],
            equipment: [],
            referenceId: "VPNiOW4mtq0VUfmBAOBB",
            reps: "10x2",
            type: "exercise",
            videoURL: "",
        },
    ],
};

//Program data
export const program = {
    imageURL:
        "https://firebasestorage.googleapis.com/v0/b/reps-699b0.appspot.com/o/43857746632.jpg?alt=media&token=6610f8ff-8951-4fbc-b12c-caea14037000",
    equipment: [],
    workouts: {
        "Week 1": [
            {
                description: "Second workout to populate the UI & database",
                title: "Second Workout",
                type: "workout",
                difficulty: "1",
                duration: "0",
                exerciseCount: 3,
                muscles: [],
                schedule: [],
                docId: "4BDnV1Pm19c2eRhh2y1h",
                imageURL: "/beachbody.jpg",
                equipment: [],
                exercises: [
                    {
                        docId: "f1b4e65b-9004-4213-8e6a-b36f83311eb1",
                        startTime: "",
                        schedule: [],
                        activity: "calisthenics",
                        type: "exercise",
                        status: 0,
                        equipment: [],
                        muscles: ["legs", "calfs"],
                        reps: "2x3",
                        referenceId: "MUATNgInAKho3nmIqq5A",
                        difficulty: "3",
                        motion: "lunges, moderate effort",
                        title: "Lunges",
                        duration: "10",
                        videoURL:
                            "https://firebasestorage.googleapis.com/v0/b/reps-699b0.appspot.com/o/24268207545.mp4?alt=media&token=a7649cc6-e5ea-4359-93fd-d2f1dfe7dd5c",
                    },
                    {
                        type: "exercise",
                        title: "Push ups",
                        activity: "calisthenics",
                        difficulty: "2.5",
                        status: 0,
                        muscles: ["biceps", "triceps", "chest"],
                        motion: "push ups, moderate effort",
                        startTime: "",
                        docId: "a73b4a82-1b29-4519-aca7-2024a52d877c",
                        schedule: [],
                        reps: "10x2",
                        referenceId: "VPNiOW4mtq0VUfmBAOBB",
                        videoURL: "",
                        equipment: [],
                        duration: "10",
                    },
                    {
                        difficulty: "2.5",
                        activity: "calisthenics",
                        type: "exercise",
                        title: "Sit ups",
                        startTime: "",
                        referenceId: "tJCpH4ZDTmuL8saZGqfR",
                        duration: "10",
                        equipment: [],
                        schedule: [],
                        muscles: ["abs"],
                        reps: "5x3",
                        status: 0,
                        motion: "sit ups, light effort",
                        videoURL: "",
                        docId: "67fd4cb7-e49e-4641-bd04-8947ac35c68b",
                    },
                ],
            },
            {
                type: "workout",
                exerciseCount: 2,
                exercises: [
                    {
                        duration: "5",
                        activity: "conditioning",
                        motion: "home exercise, general",
                        title: "Test 2",
                        reps: "1x3",
                        equipment: [],
                        referenceId: "T8Y9tKIPcR7IqySCfC2w",
                        type: "exercise",
                        status: 0,
                        startTime: "",
                        videoURL: "",
                        docId: "80eb89cf-250d-456c-b648-f50f8fd02753",
                        muscles: ["obliques", "abs", "legs"],
                        difficulty: "3",
                        schedule: [],
                    },
                    {
                        motion: "lunges, vigorous effort",
                        activity: "calisthenics",
                        status: 0,
                        reps: "2x5",
                        startTime: "",
                        equipment: [],
                        schedule: [],
                        docId: "fa532826-fdf8-4dac-b346-d48df0915b91",
                        duration: "5",
                        title: "Test exercise",
                        muscles: ["legs"],
                        referenceId: "WrfR2Cv2Prss1bd1Sfk0",
                        videoURL: "",
                        type: "exercise",
                        difficulty: "3",
                    },
                ],
                difficulty: "1",
                duration: "0",
                title: "Third workout",
                description: "Third workout",
                schedule: [],
                muscles: [],
                docId: "OZQxgKhTOMVs8mf7zBLr",
                equipment: [],
                imageURL: "/beachbody.jpg",
            },
            {
                schedule: [],
                docId: "ZGH6FQIcq6RCKI16OUwn",
                muscles: [],
                title: "First Workout",
                exercises: [
                    {
                        reps: "2x3",
                        startTime: "",
                        type: "exercise",
                        status: 0,
                        muscles: ["legs", "calfs"],
                        schedule: [],
                        equipment: [],
                        difficulty: "3",
                        referenceId: "MUATNgInAKho3nmIqq5A",
                        motion: "lunges, moderate effort",
                        activity: "calisthenics",
                        duration: "10",
                        videoURL:
                            "https://firebasestorage.googleapis.com/v0/b/reps-699b0.appspot.com/o/24268207545.mp4?alt=media&token=a7649cc6-e5ea-4359-93fd-d2f1dfe7dd5c",
                        docId: "f1b4e65b-9004-4213-8e6a-b36f83311eb1",
                        title: "Lunges",
                    },
                    {
                        activity: "calisthenics",
                        startTime: "",
                        docId: "a73b4a82-1b29-4519-aca7-2024a52d877c",
                        title: "Push ups",
                        equipment: [],
                        type: "exercise",
                        status: 0,
                        reps: "10x2",
                        difficulty: "2.5",
                        videoURL: "",
                        duration: "10",
                        referenceId: "VPNiOW4mtq0VUfmBAOBB",
                        schedule: [],
                        muscles: ["biceps", "triceps", "chest"],
                        motion: "push ups, moderate effort",
                    },
                ],
                exerciseCount: 2,
                duration: "0",
                type: "workout",
                imageURL: "/beachbody.jpg",
                description: "First workout to populate the UI & database",
                difficulty: "1",
                equipment: [],
            },
        ],
        "Week 2": [
            {
                equipment: [],
                difficulty: "1",
                description: "Third workout",
                title: "Third workout",
                duration: "0",
                docId: "OZQxgKhTOMVs8mf7zBLr",
                imageURL: "/beachbody.jpg",
                schedule: [],
                exerciseCount: 2,
                type: "workout",
                exercises: [
                    {
                        schedule: [],
                        status: 0,
                        reps: "1x3",
                        title: "Test 2",
                        equipment: [],
                        docId: "80eb89cf-250d-456c-b648-f50f8fd02753",
                        startTime: "",
                        type: "exercise",
                        videoURL: "",
                        muscles: ["obliques", "abs", "legs"],
                        difficulty: "3",
                        referenceId: "T8Y9tKIPcR7IqySCfC2w",
                        duration: "5",
                        motion: "home exercise, general",
                        activity: "conditioning",
                    },
                    {
                        activity: "calisthenics",
                        equipment: [],
                        referenceId: "WrfR2Cv2Prss1bd1Sfk0",
                        videoURL: "",
                        type: "exercise",
                        duration: "5",
                        schedule: [],
                        reps: "2x5",
                        title: "Test exercise",
                        startTime: "",
                        difficulty: "3",
                        muscles: ["legs"],
                        docId: "fa532826-fdf8-4dac-b346-d48df0915b91",
                        status: 0,
                        motion: "lunges, vigorous effort",
                    },
                ],
                muscles: [],
            },
            {
                imageURL: "/beachbody.jpg",
                muscles: [],
                description: "Second workout to populate the UI & database",
                difficulty: "1",
                schedule: [],
                type: "workout",
                exerciseCount: 3,
                equipment: [],
                duration: "0",
                exercises: [
                    {
                        muscles: ["legs", "calfs"],
                        duration: "10",
                        schedule: [],
                        equipment: [],
                        reps: "2x3",
                        startTime: "",
                        videoURL:
                            "https://firebasestorage.googleapis.com/v0/b/reps-699b0.appspot.com/o/24268207545.mp4?alt=media&token=a7649cc6-e5ea-4359-93fd-d2f1dfe7dd5c",
                        motion: "lunges, moderate effort",
                        difficulty: "3",
                        activity: "calisthenics",
                        referenceId: "MUATNgInAKho3nmIqq5A",
                        status: 0,
                        title: "Lunges",
                        docId: "f1b4e65b-9004-4213-8e6a-b36f83311eb1",
                        type: "exercise",
                    },
                    {
                        reps: "10x2",
                        duration: "10",
                        muscles: ["biceps", "triceps", "chest"],
                        startTime: "",
                        equipment: [],
                        referenceId: "VPNiOW4mtq0VUfmBAOBB",
                        type: "exercise",
                        videoURL: "",
                        difficulty: "2.5",
                        schedule: [],
                        title: "Push ups",
                        activity: "calisthenics",
                        status: 0,
                        motion: "push ups, moderate effort",
                        docId: "a73b4a82-1b29-4519-aca7-2024a52d877c",
                    },
                    {
                        duration: "10",
                        equipment: [],
                        videoURL: "",
                        motion: "sit ups, light effort",
                        startTime: "",
                        reps: "5x3",
                        difficulty: "2.5",
                        referenceId: "tJCpH4ZDTmuL8saZGqfR",
                        activity: "calisthenics",
                        title: "Sit ups",
                        muscles: ["abs"],
                        docId: "67fd4cb7-e49e-4641-bd04-8947ac35c68b",
                        status: 0,
                        type: "exercise",
                        schedule: [],
                    },
                ],
                docId: "4BDnV1Pm19c2eRhh2y1h",
                title: "Second Workout",
            },
            {
                description: "First workout to populate the UI & database",
                equipment: [],
                title: "First Workout",
                schedule: [],
                duration: "0",
                exercises: [
                    {
                        type: "exercise",
                        status: 0,
                        duration: "10",
                        docId: "f1b4e65b-9004-4213-8e6a-b36f83311eb1",
                        activity: "calisthenics",
                        schedule: [],
                        videoURL:
                            "https://firebasestorage.googleapis.com/v0/b/reps-699b0.appspot.com/o/24268207545.mp4?alt=media&token=a7649cc6-e5ea-4359-93fd-d2f1dfe7dd5c",
                        title: "Lunges",
                        motion: "lunges, moderate effort",
                        startTime: "",
                        referenceId: "MUATNgInAKho3nmIqq5A",
                        difficulty: "3",
                        equipment: [],
                        reps: "2x3",
                        muscles: ["legs", "calfs"],
                    },
                    {
                        muscles: ["biceps", "triceps", "chest"],
                        duration: "10",
                        type: "exercise",
                        schedule: [],
                        equipment: [],
                        startTime: "",
                        videoURL: "",
                        activity: "calisthenics",
                        status: 0,
                        docId: "a73b4a82-1b29-4519-aca7-2024a52d877c",
                        title: "Push ups",
                        reps: "10x2",
                        referenceId: "VPNiOW4mtq0VUfmBAOBB",
                        difficulty: "2.5",
                        motion: "push ups, moderate effort",
                    },
                ],
                type: "workout",
                exerciseCount: 2,
                muscles: [],
                docId: "ZGH6FQIcq6RCKI16OUwn",
                imageURL: "/beachbody.jpg",
                difficulty: "1",
            },
        ],
    },
    type: "program",
    description:
        "First program to add to my database but I need a bigger description for edge case purposes. You get it. Just hold on tight while I draw up this text really quick so that I can see what a few lines of text does the height of the content containerbut I need a bigger description for edge case purposes. You get it. Just hold on tight while I draw up this text really quick so that I can see what a few lines of text does the height of the content container ",
    exerciseCount: 14,
    schedule: [],
    difficulty: "2",
    duration: "0",
    workoutCount: 6,
    title: "First Program",
};

export const meals = [
    {
        title: "Immunity-Boosting Smoothe",
        imageURL:
            "https://firebasestorage.googleapis.com/v0/b/reps-699b0.appspot.com/o/smoothie.jpg?alt=media&token=68e83da3-5d8e-4195-ab1f-89989c36d0ee",
        ingredients: [
            "4 clementines, peeled",
            "1 ripe banana, sliced",
            "1 skinny carrot, peeled and shaved",
            "1 piece fresh ginger, peeled and minced",
            "1/4 cup plain yogurt",
            "pinch of salt",
            "1 tablespoon honey",
            "1 1/2 cups ice",
        ],
        directions: [
            "Add clementines, banana, carrot, ginger, yogurt, honey, salt, and ice to belender.",
            "Blend until smooth.",
            "Serve",
            "Enjoy!",
        ],
        labels: ["Vegetarian", "Gluten Free", "Healthy choice"],
        nutrition: {
            Protein: 9,
            Fat: 2,
            Sugar: 84,
            Fiber: 13,
            Carbs: 120,
            Calories: 491,
        },
        rating: 4.7,
        type: "snack",
    },
    {
        title: "Chicken & Veggie Stir-Fry",
        imageURL:
            "https://firebasestorage.googleapis.com/v0/b/reps-699b0.appspot.com/o/chicken%26veggie.jpg?alt=media&token=2f7db04a-c475-4a43-a586-23f3872bb71e",
        ingredients: [
            "1 lb chicken breast, cubed",
            "1 lb broccoli florets",
            "salt, to taste",
            "pepper, to taste",
            "3 tablespoons oil, for frying",
            "3 cloves garlic, minced",
            "1 tablespoon ginger, minced",
            "1 cup chicken broth",
            "2 teaspoons sesame oil",
            "¼ cup flour",
            "⅓ cup reduced sodium soy sauce",
        ],
        directions: [
            "In a large pan on medium-high heat, add 1 tablespoon of oil. Once the oil is hot, add chicken, season with salt and pepper, and sauté until cooked through and browned. Remove cooked chicken from pan and set aside. In the same pan, heat 1 tablespoon of oil and add mushrooms. When the mushrooms start to soften, add broccoli florets and stir-fry until the broccoli is tender. Remove cooked mushrooms and broccoli from the pan and set aside.",
            "Add 1 tablespoon of oil to the pan and sauté garlic and ginger until fragrant. Add the remaining sauce ingredients and stir until smooth.",
            "Return the chicken and vegetables to the saucy pan, stir until heated through.",
            "Serve with hot rice or noodles.",
            "Enjoy!",
        ],
        labels: ["Healthy Choice", "Meal Prep"],
        nutrition: {
            Carbs: 23,
            Fiber: 2,
            Protein: 27,
            Calories: 393,
            Fat: 20,
            Sugar: 4,
        },
        rating: 4.7,
        type: "dinner",
    },
];
