export const SET_WORKOUTS = "SET_WORKOUTS";
export const ADD_WORKOUT = "ADD_WORKOUT";
export const DELETE_WORKOUT = "DELETE_WORKOUT";
export const UPDATE_NEW_WORKOUT = "UPDATE_NEW_WORKOUT";
export const CLEAR_NEW_WORKOUT = "CLEAR_NEW_WORKOUT";
