export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_USER = "SET_USER";
export const UPDATE_USER_DATA = "UPDATE_USER_DATA";
export const LOADING_USER = "LOADING_USER";
export const SET_USERS = "SET_USERS";
export const CLEAR_USER = "CLEAR_USER";
